### ISSUE TITLE
proposal: streaming reader as Searcher param

### ISSUE THREAD

**Issue by rocaltair** [bytedance/sonic#147]
https://github.com/bytedance/sonic/blob/d2711a6af0e3bcc2015f9058297c2eb013e621e2/ast/search.go#L33

say `response.Body`  is a stream as io.Reader, shall we just parse the stream to avoid large memory allocation on searching?

example:

```
resp, err := httpClient.Do(req)
// handle err
defer resp.Body.Close()
searcher := NewStreamSearcher(resp.Body)
node, err := searcher.GetPath("foo", "bar", "largePayload")
// handle error
io.Copy(writer, node.GetStream())
```

**Comment by chenzhuoyu** [comment]
Not very possible.

One of the reason Sonic is so fast, is that it uses SIMD instructions to accelerate string processing, which require contiguous memory with known size. Streams work with bytes, and do not have predetermined length, which is not very compatible with SIMD instructions.

You can use a pool of some kind (like `sync.Pool`) to manage the JSON string buffer for you, it also helps with memory allocation.

Also, because of the delimiter-based nature of JSON, it is not a very Stream-friendly format per-se.

**Comment by rocaltair** [comment]
got it. 

while,  in fact `sync.Pool` does little help, especially on IoT device with few memory.

thanks anyway.
