### ISSUE TITLE
Dismatched field type with json value will return error “invalid char” and stop decoding

### ISSUE THREAD

**Issue by ruikc** [bytedance/sonic#298]
使用官方的json库，可以使用，但切换成sonic就会报这个错误。
message: ""Syntax error at index 175: invalid char\n\n\t,\"nuclein_addr\":\"\",\"nuclein_reas\n\t................^...............\n""

**Comment by AsterDY** [comment]
一般是类型不匹配，标准库也报错了但不会停止解析。建议检查错误并对字段类型进行严格匹配

**Comment by AsterDY** [comment]
For example, if field 'A' is declared as type `int` while matched json key comes with a string value `"1"`, sonic will regard it as a syntax error and stop continuing decoding. This is the same with `json-iterator` but different with `encoding/json`. Since the std document mentioned this behavior as **not guaranteed** （see [json.Unmarshal](https://pkg.go.dev/encoding/json#Unmarshal)), we decided not to support this feature at present.

**Comment by AsterDY** [comment]
#321 resloved
