### ISSUE TITLE
ci: add performance diff test in github CI

### ISSUE THREAD

**Issue by liuq19** [bytedance/sonic#413]
We need add a performance diff test through the  [bench.py](https://github.com/bytedance/sonic/blob/main/bench.py) or other tools, and make it in github workflow.

**Comment by sswastik02** [comment]
Hi @liuq19 ! I noticed this issue has been open for a while without any activity. I'd be interested in working on this. 
I'd love to contribute and help move this forward.

**Comment by liuq19** [comment]
Thanks, welcome to try it ~

**Comment by sswastik02** [comment]
Thank you for providing this opportunity to contribute.

> We need add a performance diff test through the [bench.py](https://github.com/bytedance/sonic/blob/main/bench.py) or other tools, and make it in github workflow.

However, it seems that the provided URL for the bench.py file does not lead to a valid GitHub file location. Could you kindly provide the correct URL so that I can proceed with the necessary steps? Your assistance in clarifying this matter would be greatly appreciated.

**Comment by liuq19** [comment]
yes, the file is  [benc.py](https://github.com/bytedance/sonic/blob/test/go121/bench.py)

**Comment by sswastik02** [comment]
Hey @liuq19 , I tried running the file on my system, it takes a really long time to execute, is there specific flags that i need to pass to it ? 
Also is the performance diff mainly for the pull requests? as in the performance diff between branches ?

**Comment by liuq19** [comment]
pls provide more details, maybe capture or some logs. To make me can reproduce that
